CREATE DATABASE FOODIE;

USE FOODIE;

CREATE TABLE RESTAURANTS (
	NAME_RESTAURANT VARCHAR(50) PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    PW VARCHAR(64) NOT NULL,
    ADDRESS VARCHAR(256) NOT NULL,
    PHONE BIGINT NOT NULL
);

CREATE TABLE USERS (
	NAME_USER VARCHAR(64) NOT NULL,
    SURNAME_USER VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(256) PRIMARY KEY NOT NULL,
    PW VARCHAR(64) NOT NULL,
    ADDRESS VARCHAR(256) NOT NULL,
    PHONE BIGINT NOT NULL
);

CREATE TABLE ORDERS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    EMAIL_USER VARCHAR(256) NOT NULL,
    ID_RIDER INT,
    FOREIGN KEY(ID_RIDER) REFERENCES RIDERS(ID),
    FOREIGN KEY(EMAIL_USER) REFERENCES USERS(EMAIL)
);

CREATE TABLE ITEMS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME_ITEM VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(256),
	NAME_RESTAURANT VARCHAR(50) NOT NULL,
    FOREIGN KEY(NAME_RESTAURANT) REFERENCES RESTAURANTS(NAME_RESTAURANT)
);

CREATE TABLE RIDERS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PHONE BIGINT NOT NULL
);

CREATE TABLE ITEMSORDERS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_ITEM INT NOT NULL,
    ID_ORDER INT NOT NULL,
    FOREIGN KEY(ID_ITEM) REFERENCES ITEMS(ID),
    FOREIGN KEY(ID_ORDER) REFERENCES ORDERS(ID)
);
